=== Rubencito2002/2-DAW/HLC/XSD/Actividad 1/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name='portes' type='PortesType' />
    <xs:complexType name='PortesType'>
        <xs:choice minOccurs='0' maxOccurs='unbounded'>
            <xs:element name='recepcion' type='RecepcionType' />
            <xs:element name='entrega' type='EntregaType' />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name='RecepcionType'>
        <xs:sequence>
            <xs:element name='producto' type='xs:string' />
            <xs:element name='cantidad' type='xs:positiveInteger' />
            <xs:element name='codigoReceptor' type='CodigoReceptorType' minOccurs='0' />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name='EntregaType'>
        <xs:sequence>
            <xs:element name='transportista' type='TransportistaType' />
            <xs:element name='distancia' type='DistanciaType' />
            <xs:element name='coste' type='xs:positiveInteger' />
        </xs:sequence>
        <xs:attribute name="receptor" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name=''>
        <xs:restriction base='xs:string'>
            <xs:pattern value="\d{3}-[A-Z]{3}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TransportistaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="T1"/>
            <xs:enumeration value="T2"/>
            <xs:enumeration value="T3"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="DistanciaType">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="unidad" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== Rubencito2002/2-DAW/HLC/XSD/Actividad 1/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<portes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedidos.xsd">
    <recepcion>
        <producto> Producto1 </producto>
        <cantidad> 5 </cantidad>
        <codigoReceptor> 123-ABC </codigoReceptor>
    </recepcion>
    <entrega receptor='Receptor1'>
        <transportista> T1 </transportista>
        <distancia unidad='kilometros'> 50 </distancia>
        <coste> 100 </coste>
    </entrega>
    <recepcion>
        <producto> Producto2 </producto>
        <cantidad> 3 </cantidad>
    </recepcion>
</portes>
