=== Rubencito2002/2-DAW/HLC/XML/Practica 1/Actividad 1/empresa.dtd
<!ELEMENT empresa (trabajadores)+>
<!ELEMENT trabajadores (trabajador)+>
<!ELEMENT trabajador (departamento, nombre, apellidos, cargo+, telefono-movil+, telefono-fijo?)>
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>
<!ELEMENT telefono-fijo (#PCDATA)>
<!ELEMENT telefono-movil (#PCDATA)>

=== Rubencito2002/2-DAW/HLC/XML/Actividad 1/empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilos.css"?>
<!DOCTYPE empresa SYSTEM "empresa.dtd">
<empresa>
    <trabajadores>
        <trabajador>
            <departamento>Nombre del departamento: Informatica</departamento>
            <nombre-completo> Nombre y Apellidos:
                <nombre>Juan</nombre>
                <apellidos>PÃ©rez</apellidos>
            </nombre-completo>
            <cargo>Cargo: Desarrollador</cargo>
            <cargo>Cargo: Analista</cargo>
            <telefono-movil>Telefono movil: 123456789</telefono-movil>
            <telefono-movil>Telefono movil: 987654321</telefono-movil>
            <telefono-fijo>Telefono fjo: 012345678</telefono-fijo>
        </trabajador>
        <trabajador>
            <departamento>Nombre del departamento: Informatica</departamento>
            <nombre-completo> Nombre y Apellidos:
                <nombre>Laura</nombre>
                <apellidos>Sanchez</apellidos>
            </nombre-completo>
            <cargo>Cargo: Desarrollador</cargo>
            <cargo>Cargo: Analista</cargo>
            <telefono-movil>Telefono movil: 123456789</telefono-movil>
            <telefono-movil>Telefono movil: 987654321</telefono-movil>
        </trabajador>
    </trabajadores>
</empresa>
