=== Rubencito2002/2-DAW/HLC/JSON/Practica 1/Ejercicio 2/pokemon.dtd
<!ELEMENT pokemon (nombre, ataques, tipos, peso, imagenes)>
<!ELEMENT nombrePokemon (#PCDATA)>
<!ELEMENT ataques (ataque+)>
<!ELEMENT ataque (nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipos (tipo+)>
<!ELEMENT tipo (nombre)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT imagenes (imagen_delantera, imagen_trasera)>
<!ELEMENT imagen_delantera (#PCDATA)>
<!ELEMENT imagen_trasera (#PCDATA)>

=== Rubencito2002/2-DAW/HLC/JSON/Practica 1/Ejercicio 2/pokemon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pokemon SYSTEM "pokemon.dtd">
<pokemon>
    <nombrePokemon> bulbasaur </nombrePokemon>
    <ataques> 
        <ataque>
            <nombre> razor-wind </nombre>
        </ataque>
        <ataque>
            <nombre> swords-dance </nombre>
        </ataque>
        <ataque>
            <nombre> bind </nombre>
        </ataque>
        <ataque>
            <nombre> vine-whip </nombre>
        </ataque>
        <ataque>
            <nombre> headbutt </nombre>
        </ataque>
        <ataque>
            <nombre> tackle </nombre>
        </ataque>
    </ataques>
    <tipos>
        <tipo>
            <nombre> grass </nombre>
        </tipo>
        <tipo>
            <nombre> poison </nombre>
        </tipo>
    </tipos>
    <peso> 69 </peso>
    <imagenes>
        <imagen_delantera> https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png </imagen_delantera>
        <imagen_trasera> https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/1.png </imagen_trasera>
    </imagenes>
</pokemon>
